"""create chat room table

Revision ID: 0de99ba4d60c
Revises: 9b5d9e03eba9
Create Date: 2025-06-11 08:16:59.403565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de99ba4d60c'
down_revision: Union[str, None] = '9b5d9e03eba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_chat_rooms_creator_id'), 'chat_rooms', ['creator_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_room_id'), 'chat_rooms', ['room_id'], unique=False)
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_index(op.f('ix_chat_rooms_room_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_creator_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
