"""move_profile_picture_url_to_userprofile

Revision ID: 3212fe8838e2
Revises: 803c93710e8e
Create Date: 2025-09-03 20:45:43.100016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3212fe8838e2'
down_revision: Union[str, None] = '803c93710e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'profile_picture_url')
    # ### end Alembic commands ###
