"""add_additional_fields_to_chat_room

Revision ID: 3c6688d82f3a
Revises: 3212fe8838e2
Create Date: 2025-09-03 21:53:12.842356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6688d82f3a'
down_revision: Union[str, None] = '3212fe8838e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('chat_rooms', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('chat_rooms', sa.Column('max_participants', sa.Integer(), nullable=True))
    op.add_column('chat_rooms', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('chat_rooms', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_rooms', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, server_onupdate=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'updated_at')
    op.drop_column('chat_rooms', 'settings')
    op.drop_column('chat_rooms', 'avatar_url')
    op.drop_column('chat_rooms', 'max_participants')
    op.drop_column('chat_rooms', 'is_private')
    op.drop_column('chat_rooms', 'description')
    # ### end Alembic commands ###
