"""add_is_direct_message_column

Revision ID: 3e95d18d2612
Revises: 3c6688d82f3a
Create Date: 2025-12-21 14:47:24.193848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e95d18d2612'
down_revision: Union[str, None] = '3c6688d82f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('is_direct_message', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_chat_rooms_is_direct_message'), 'chat_rooms', ['is_direct_message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_rooms_is_direct_message'), table_name='chat_rooms')
    op.drop_column('chat_rooms', 'is_direct_message')
    # ### end Alembic commands ###
