"""update_notification_table_add_is_read_and_updated_at

Revision ID: d5ab82a12ab7
Revises: 4b1f838d6bd2
Create Date: 2025-07-27 20:55:53.329835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ab82a12ab7'
down_revision: Union[str, None] = '4b1f838d6bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'content',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###
